server {
    listen 80;
    root /usr/share/nginx/html;

    location /api/ {
        proxy_pass http://api:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Trace-Id $http_x_trace_id;
        proxy_read_timeout 60s;
    }

    location / {
        try_files $uri /index.html;
    }
}
